
- name: send email via SendGrid if file not downloaded
  local_action: 
    module: sendgrid
    username: "{{ sendgrid_username }}"
    password: "{{ sendgrid_password }}"
    from_address: "{{ sendgrid_from_address }}"
    to_addresses: "{{ sendgrid_to_addresses }}"
    subject: "{{ sendgrid_subject }}"
    body: "Failed to download file from {{ site_tarball }}." 
  when: not download_file.stat.exists

