- name: send phone an alert text via Twilio if file not create
  local_action: 
    module: twilio
    account_sid: "{{ twilio_account_sid }}"
    auth_token: "{{ twilio_auth_token }}"
    msg: "Failed to download file from {{ site_tarball }}." 
    from_number: "{{ twilio_number }}"
    to_number: "{{ alert_number }}"
  when: not download_file.stat.exists

